/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as CartaRouteImport } from './routes/carta'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPanelFrankys2847RouteImport } from './routes/_authenticated/panel-frankys-2847'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const CartaRoute = CartaRouteImport.update({
  id: '/carta',
  path: '/carta',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPanelFrankys2847Route =
  AuthenticatedPanelFrankys2847RouteImport.update({
    id: '/panel-frankys-2847',
    path: '/panel-frankys-2847',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carta': typeof CartaRoute
  '/manage': typeof ManageRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/panel-frankys-2847': typeof AuthenticatedPanelFrankys2847Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carta': typeof CartaRoute
  '/manage': typeof ManageRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/panel-frankys-2847': typeof AuthenticatedPanelFrankys2847Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/carta': typeof CartaRoute
  '/manage': typeof ManageRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/panel-frankys-2847': typeof AuthenticatedPanelFrankys2847Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/carta' | '/manage' | '/sitemap.xml' | '/panel-frankys-2847'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/carta' | '/manage' | '/sitemap.xml' | '/panel-frankys-2847'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/carta'
    | '/manage'
    | '/sitemap.xml'
    | '/_authenticated/panel-frankys-2847'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CartaRoute: typeof CartaRoute
  ManageRoute: typeof ManageRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carta': {
      id: '/carta'
      path: '/carta'
      fullPath: '/carta'
      preLoaderRoute: typeof CartaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/panel-frankys-2847': {
      id: '/_authenticated/panel-frankys-2847'
      path: '/panel-frankys-2847'
      fullPath: '/panel-frankys-2847'
      preLoaderRoute: typeof AuthenticatedPanelFrankys2847RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPanelFrankys2847Route: typeof AuthenticatedPanelFrankys2847Route
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPanelFrankys2847Route: AuthenticatedPanelFrankys2847Route,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CartaRoute: CartaRoute,
  ManageRoute: ManageRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
